version: "3.8"

services:
  logstash:
    image: opensearchproject/logstash-oss-with-opensearch-output-plugin:latest
    container_name: logstash
    command: logstash -f /usr/share/logstash/pipeline/teleport-audit.conf # pipeline 설정 파일을 지정함.
    volumes:
      - ./pipeline:/usr/share/logstash/pipeline
      - ./config:/usr/share/logstash/config
      - /Users/choijeongsik/Desktop/log-audit/data/logs:/teleport-logs # teleport 로그를 도커에 mount.
    ports:
      - "5001:5000"
#    depends_on:
#      - opensearch-node1  # 기존 OpenSearch 컨테이너 이름
    networks:
      - opensearch-net

networks:
  opensearch-net:
    external: true